#!/usr/bin/env python3
"""
Regenerate every chart artefact on the JEVIS page from data/results.json.

    python3 tools/make_charts.py

Outputs
  static/js/results-data.js   -> window.JEVIS_RESULTS (feeds the interactive Chart.js radar)
  figs/charts/radar_*.svg/png -> static radar charts (one per dataset + dataset average, per setting)
  figs/charts/ause_bars.svg/png -> uncertainty-quantification bars (AUSE-D / AUSE-V)

Radar normalisation: for every axis the seven methods are min-max normalised
(LPIPS / AUSE inverted so that farther from the centre is always better) and mapped
to the ring [0.22, 1.0] so the worst method is still a visible polygon.
"""
import json
import math
import os
import re
import sys

import numpy as np
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
from matplotlib.lines import Line2D  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "data", "results.json")
OUT_JS = os.path.join(ROOT, "static", "js", "results-data.js")
OUT_DIR = os.path.join(ROOT, "figs", "charts")

# --- palette (validated with the dataviz palette checker, all-pairs, light surface) ---
STYLE = {
    "JEVIS":       dict(color="#2a78d6", lw=2.6, ls="-",  fill=0.22, z=10),
    "GAVIS":       dict(color="#eb6834", lw=1.8, ls="-",  fill=0.0,  z=6),
    "MAGICIAN":    dict(color="#1baf7a", lw=1.8, ls="-",  fill=0.0,  z=5),
    "COVER":       dict(color="#4a3aa7", lw=1.8, ls="-",  fill=0.0,  z=4),
    "VIMC":        dict(color="#898781", lw=1.4, ls="-",  fill=0.0,  z=3),
    "BB+FisherRF": dict(color="#898781", lw=1.4, ls="--", fill=0.0,  z=2),
    "FisherRF":    dict(color="#898781", lw=1.4, ls=":",  fill=0.0,  z=1),
}
INK = "#0b0b0b"
INK2 = "#52514e"
MUTED = "#898781"
GRID = "#e1e0d9"
SURFACE = "#ffffff"
R_MIN, R_MAX = 0.22, 1.0

plt.rcParams.update({
    "font.family": "sans-serif",
    "font.sans-serif": ["Inter", "Helvetica Neue", "Helvetica", "Arial", "DejaVu Sans"],
    "svg.fonttype": "none",
    "figure.dpi": 100,
    "savefig.dpi": 200,
})


def load():
    with open(DATA) as f:
        return json.load(f)


def write_js(d):
    os.makedirs(os.path.dirname(OUT_JS), exist_ok=True)
    with open(OUT_JS, "w") as f:
        f.write("// GENERATED by tools/make_charts.py from data/results.json - do not edit by hand.\n")
        f.write("window.JEVIS_RESULTS = ")
        json.dump(d, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")
    print("wrote", os.path.relpath(OUT_JS, ROOT))


def block_values(d, setting, dataset_key):
    """Return {method: {metric: mean}} for one setting/dataset, or the dataset average."""
    methods = d["methods"]
    mkeys = [m["key"] for m in d["metrics"]]
    ds_keys = [x["key"] for x in d["datasets"]]
    out = {}
    for m in methods:
        out[m] = {}
        for mk in mkeys:
            if dataset_key == "avg":
                out[m][mk] = float(np.mean([d["settings"][setting][ds][m][mk][0] for ds in ds_keys]))
            else:
                out[m][mk] = d["settings"][setting][dataset_key][m][mk][0]
    return out


def normalise(values, metrics):
    """values: {method: {metric: v}} -> {method: [r per metric]} in [R_MIN, R_MAX]."""
    res = {m: [] for m in values}
    for met in metrics:
        col = np.array([values[m][met["key"]] for m in values], dtype=float)
        lo, hi = col.min(), col.max()
        span = hi - lo if hi > lo else 1.0
        for i, m in enumerate(values):
            s = (col[i] - lo) / span
            if not met["higher_is_better"]:
                s = 1.0 - s
            res[m].append(R_MIN + (R_MAX - R_MIN) * s)
    return res


def radar(d, setting, dataset_key, path_base, title):
    metrics = d["metrics"]
    labels = [m["label"] for m in metrics]
    n = len(metrics)
    angles = np.linspace(0, 2 * math.pi, n, endpoint=False)
    angles_closed = np.concatenate([angles, angles[:1]])

    values = block_values(d, setting, dataset_key)
    norm = normalise(values, metrics)

    fig = plt.figure(figsize=(5.6, 5.9))
    ax = fig.add_axes([0.10, 0.20, 0.80, 0.70], polar=True)
    ax.set_facecolor(SURFACE)
    fig.patch.set_facecolor(SURFACE)
    ax.set_theta_offset(math.pi / 2)
    ax.set_theta_direction(-1)
    ax.set_ylim(0, 1.04)
    ax.set_yticks([0.25, 0.5, 0.75, 1.0])
    ax.set_yticklabels([])
    ax.yaxis.grid(True, color=GRID, lw=0.8)
    ax.xaxis.grid(True, color=GRID, lw=0.8)
    ax.spines["polar"].set_color(GRID)
    ax.spines["polar"].set_linewidth(0.8)
    ax.set_xticks(angles)
    ax.set_xticklabels(labels, fontsize=11, color=INK)
    for lab, ang in zip(ax.get_xticklabels(), angles):
        lab.set_y(lab.get_position()[1] - 0.02)
    ax.tick_params(pad=12)

    # draw the recessive baselines first, JEVIS last so it sits on top
    order = sorted(d["methods"], key=lambda m: STYLE[m]["z"])
    for m in order:
        st = STYLE[m]
        r = np.array(norm[m] + norm[m][:1])
        ax.plot(angles_closed, r, color=st["color"], lw=st["lw"], ls=st["ls"], zorder=st["z"], solid_capstyle="round")
        if st["fill"] > 0:
            ax.fill(angles_closed, r, color=st["color"], alpha=st["fill"], zorder=st["z"] - 0.5)
        if m == d["ours"]:
            ax.scatter(angles, norm[m], s=28, color=st["color"], zorder=st["z"] + 1, edgecolors=SURFACE, linewidths=1.5)

    ax.set_title(title, fontsize=13, color=INK, pad=22, fontweight="bold")

    # reading order (row-major) = strongest first; matplotlib fills legends column-major, so interleave
    reading = ["JEVIS", "GAVIS", "MAGICIAN", "COVER", "VIMC", "BB+FisherRF", "FisherRF"]
    reading = [m for m in reading if m in d["methods"]] + [m for m in d["methods"] if m not in reading]
    ncol = 4
    nrow = math.ceil(len(reading) / ncol)
    col_major = []
    for c in range(ncol):
        for r in range(nrow):
            i = r * ncol + c
            if i < len(reading):
                col_major.append(reading[i])
    handles = [
        Line2D([0], [0], color=STYLE[m]["color"], lw=STYLE[m]["lw"], ls=STYLE[m]["ls"],
               label=(m + " (ours)" if m == d["ours"] else m))
        for m in col_major
    ]
    fig.legend(handles=handles, loc="lower center", ncol=ncol, frameon=False, fontsize=9.5,
               labelcolor=INK2, bbox_to_anchor=(0.5, 0.02), handlelength=2.2, columnspacing=1.4)
    fig.text(0.5, 0.115, "Axes min–max normalised across methods; farther from the centre is better.",
             ha="center", fontsize=8.5, color=MUTED)

    for ext in ("svg", "png"):
        p = path_base + "." + ext
        fig.savefig(p, facecolor=SURFACE, bbox_inches="tight", pad_inches=0.15)
        if ext == "svg":
            _fix_svg_fonts(p)
    plt.close(fig)
    print("wrote", os.path.relpath(path_base, ROOT) + ".{svg,png}")


def ause_bars(d, path_base):
    methods = d["methods"]
    mets = d["ause"]["metrics"]
    vals = d["ause"]["values"]
    fig, axes = plt.subplots(1, len(mets), figsize=(8.2, 3.4), sharey=False)
    fig.patch.set_facecolor(SURFACE)
    # one fixed row order for every panel (best AUSE-D at the top) so rows line up across panels
    order = sorted(methods, key=lambda m: vals[m][mets[0]["key"]])
    for ax, met in zip(np.atleast_1d(axes), mets):
        ax.set_facecolor(SURFACE)
        y = np.arange(len(order))
        for i, m in enumerate(order):
            v = vals[m][met["key"]]
            c = STYLE[m]["color"] if m in ("JEVIS", "GAVIS", "MAGICIAN", "COVER") else "#c3c2b7"
            ax.barh(i, v, height=0.5, color=c, zorder=3)
            ax.text(v + 0.012, i, f"{v:.3f}", va="center", fontsize=9, color=INK2)
        ax.invert_yaxis()
        ax.set_yticks(y)
        ax.set_yticklabels([(m + " (ours)" if m == d["ours"] else m) for m in order], fontsize=9.5, color=INK)
        ax.set_xlim(0, 0.68)
        ax.set_xlabel(met["label"] + "  (lower is better)", fontsize=10, color=INK2)
        ax.xaxis.grid(True, color=GRID, lw=0.8, zorder=0)
        ax.set_axisbelow(True)
        for s in ("top", "right", "left"):
            ax.spines[s].set_visible(False)
        ax.spines["bottom"].set_color(GRID)
        ax.tick_params(axis="x", colors=MUTED, labelsize=8.5)
        ax.tick_params(axis="y", length=0)
    fig.suptitle("Joint uncertainty quantification (AUSE, lower is better)", fontsize=12, color=INK, fontweight="bold")
    fig.tight_layout(rect=(0, 0, 1, 0.94))
    for ext in ("svg", "png"):
        p = path_base + "." + ext
        fig.savefig(p, facecolor=SURFACE, bbox_inches="tight", pad_inches=0.15)
        if ext == "svg":
            _fix_svg_fonts(p)
    plt.close(fig)
    print("wrote", os.path.relpath(path_base, ROOT) + ".{svg,png}")


def _fix_svg_fonts(path):
    """matplotlib writes the resolved fallback font name; make the SVG ask for the page font first."""
    with open(path) as f:
        s = f.read()
    s = re.sub(r"font-family:\s*'?DejaVu Sans'?", "font-family: Inter, system-ui, -apple-system, 'Segoe UI', sans-serif", s)
    s = re.sub(r"font-family:\s*'?(Helvetica Neue|Helvetica|Arial)'?", "font-family: Inter, system-ui, -apple-system, 'Segoe UI', sans-serif", s)
    with open(path, "w") as f:
        f.write(s)


def main():
    d = load()
    write_js(d)
    os.makedirs(OUT_DIR, exist_ok=True)
    ds_labels = {x["key"]: x["label"] for x in d["datasets"]}
    for setting in ("single", "multi"):
        slabel = d["settings"][setting]["label"]
        radar(d, setting, "avg", os.path.join(OUT_DIR, f"radar_{setting}_avg"), f"{slabel} · average over datasets")
        for ds in ds_labels:
            radar(d, setting, ds, os.path.join(OUT_DIR, f"radar_{setting}_{ds}"), f"{slabel} · {ds_labels[ds]}")
    ause_bars(d, os.path.join(OUT_DIR, "ause_bars"))


if __name__ == "__main__":
    sys.exit(main())
